### ISSUE TITLE
"Affordable"

### ISSUE THREAD

**Issue by Caroline-A** [SDGforskning/SDGstrings_wos#11]
We should perhaps compare search strings for targets that include "affordable". Add targets where affordable is included under:

- 3.8 (also added to 3.7 but more as an element of universal access, "affordable" not in the target)
- 4.3
- 7.1
- 11.1
- 11.2

**Comment by Caroline-A** [comment]
I've added some terms for this now in the vocab list

**Comment by ingerg** [comment]
Affordable is included in the targets:

3.8
3.b
3.b.3
4.3
6.1
7
7.1
9.1
9.3
9.c
11.1
11.2
