### ISSUE TITLE
Terms for vulnerable groups

### ISSUE THREAD

**Issue by Caroline-A** [SDGforskning/SDGstrings_wos#7]
We need to check how "vulnerable groups" are defined. They are likely to be different between SDGs, but it would be good to check:
- How have we defined these? Have we got sources?
- How do they compare across SDGs?

**Comment by Caroline-A** [comment]
Maybe helpful documents:
- https://www.undrr.org/publication/marginalized-and-minority-groups-consideration-ndra
- https://www.ohchr.org/en/special-procedures/sr-health/non-discrimination-groups-vulnerable-situations

**Comment by Caroline-A** [comment]
https://www.un.org/en/desa/leaving-no-one-behind

**Comment by ingerg** [comment]
Vulnerable groups is included in the targets:

1.3 Implement nationally appropriate social protection systems and measures for all, including floors, and by 2030 achieve substantial coverage of the poor and the vulnerable

1.4 By 2030, ensure that all men and women, in particular the poor and the vulnerable, have equal rights to economic resources, as well as access to basic services, ownership and control over land and other forms of property, inheritance, natural resources, appropriate new technology and financial services, including microfinance

1.5 By 2030, build the resilience of the poor and those in vulnerable situations and reduce their exposure and vulnerability to climate-related extreme events and other economic, social and environmental shocks and disasters

2.1 By 2030, end hunger and ensure access by all people, in particular the poor and people in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round

11.2 By 2030, provide access to safe, affordable, accessible and sustainable transport systems for all, improving road safety, notably by expanding public transport, with special attention to the needs of those in vulnerable situations, women, children, persons with disabilities and older persons

11.5 By 2030, significantly reduce the number of deaths and the number of people affected and substantially decrease the direct economic losses relative to global gross domestic product caused by disasters, including water-related disasters, with a focus on protecting the poor and people in vulnerable situations

**Comment by EliSeland** [comment]
Also 4.5:
4.5 By 2030, eliminate gender disparities in education and ensure equal access to all levels of education and vocational training for the vulnerable, including persons with disabilities, indigenous peoples and children in vulnerable situations

**Comment by ingerg** [comment]
vulnerable groups include:

- children
- infants
- women
- youth
- persons with disabilities
- people living with HIV/AIDS
- older persons
- indigenous peoples
- ethnic minorities
- refugees 
- internally displaced persons
- migrants
- asylum-seekers
- sexual minorities
- LGBTI persons

**Comment by Caroline-A** [comment]
Just a thought, the existing terms here might help with making a string for some of these: https://github.com/SDGforskning/Resources/blob/main/Vocabularylist.md#groups-of-people

**Comment by ingerg** [comment]
Takk Caroline,

Vi skal se på dette.

Hilsen
Inger 😊

Fra: Caroline Armitage ***@***.***>
Sendt: torsdag 5. mai 2022 16:09
Til: SDGforskning/SDGstrings_wos ***@***.***>
Kopi: Inger Gåsemyr ***@***.***>; Assign ***@***.***>
Emne: Re: [SDGforskning/SDGstrings_wos] Terms for vulnerable groups (Issue #7)


Just a thought, the existing terms here might help with making a string for some of these: https://github.com/SDGforskning/Resources/blob/main/Vocabularylist.md#groups-of-people

**Comment by ingerg** [comment]
I have made this string for vulnarable groups:

((("person$" OR "people" OR "adult$") NEAR/3 ("disabled" OR "disabilities" OR "patient$" OR "unemployed" OR "older" OR "elderly" OR "indigenous" OR "living with HIV/AIDS" OR "living in poverty" OR discriminated OR poor OR poorest)) OR "ethnic minorit*" OR "refugee$" OR "migrant$" OR "asylum-seeker$" OR child OR children OR "infant$" OR "babies" OR "newborn$" OR "toddler$" OR "youth$" "women" OR "woman" OR "pregnant" OR "sexual minorit*" OR "vulnerable" OR "vulnerable group$")

**Comment by Caroline-A** [comment]
@ingerg I'd like to suggest a slight edit, to combine some of the terms we have already used in SDG1 and maybe add a bit more flexibility by including some of the terms both with "people" and with "groups". 

In testing for SDG1 we found that "vulnerable" alone is too broad in some cases (e.g. vulnerable habitats), so I've edited it to "the vulnerable" as a default, is that ok?

For example, something like (?):
``` 
(
(
   ("person$" OR "people" OR "adult$") 
   NEAR/3 ("disabled" OR "disabilities" OR "disability" OR "patient$" OR "unemployed" OR "older" OR "elderly" OR "indigenous"  OR "discriminated" OR "poor" OR "poorest" OR "vulnerable" OR "marginali$ed")
) 
OR "ethnic minorit*" OR "sexual minorit*" OR "minority group$"
OR "refugee$" OR "migrant$" OR "immigrant$" OR "asylum-seeker$" 
OR "indigenous group$" 
OR "child" OR "children" OR "infant$" OR "babies" OR "newborn$" OR "toddler$" OR "youth$" 
OR "women" OR "woman" OR "pregnant" 
OR "living with HIV" OR "living with AIDS"
OR "the vulnerable" OR "vulnerable group$" OR "vulnerable communit*" OR "marginali?ed group$" OR "marginali$ed communit*"
OR "the poor" OR "rural poor" OR "urban poor" OR "working poor" OR "destitute" OR "living in poverty" 
)
```

**Comment by EliSeland** [comment]
I have a few comments here, too, after working with this in 4.3. 

I found that "asylum*" included relevant hits that were not found when using "asylum-seeker$" (and in my case, no noise).

I also found "displaced" to be a useful synonym to refugees, migrants etc, and "low* income" added some hits in addition to the variants of "poor", "poverty" etc. " And I used "disadvantaged" alongside disabled etc.

I don't know if these have been tested/considered?

**Comment by Caroline-A** [comment]
So that we don't all have to repeat work in the documentation, here are the central sources Inger mentioned :)) You can copy paste from the "edit" view of this comment.

> The terms for *vulnerable groups* are based on the groups mentioned in the indicator for 1.3 as well as several sources from the UN (<a id="Blanchard">[Blanchard et al., 2017](#f12)</a>; <a id="UNOHC">[Office of the High Commissioner, n.d.](#f13)</a>; <a id="UNracism">[United Nations, n.d.](#f14)</a>)
> 
> _Footnotes:_
> <a id="f12"></a> Blanchard et al. (2017). *Words into action guidelines: National Disaster Risk Assessment. Special Topics: K. Consideration of Marginalized and Minority Groups in a National Disaster Risk Assessment*. United Nations Office for Disaster Risk Reduction. https://www.undrr.org/publication/marginalized-and-minority-groups-consideration-ndra. [↩](#Blanchard)
> <a id="f13"></a> Office of the High Commissioner (n.d.) *Non-discrimination: Groups in vulnerable situations. Special Rapporteur on the right to health*. United Nations Human Rights. https://www.ohchr.org/en/special-procedures/sr-health/non-discrimination-groups-vulnerable-situations (accessed Jun 2022). [↩](#UNOHC)
> <a id="f14"></a> United Nations (n.d.) *Fight racism. Vulnerable groups, who are they?*. https://www.un.org/en/fight-racism/vulnerable-groups?gclid=EAIaIQobChMI9ODI_PvC9wIVV53VCh3pQgZCEAAYASAAEgInB_D_BwE (accessed Jun 2022). [↩](#UNracism)

**Comment by Caroline-A** [comment]
Great! But I also suddenly had a thought, in addition to having "LGBT*" we should write them out, as there will be research that references one of the groups without using this acronym. I've added some terms as standalone, and some combined with the "people" part. e.g.

```Ceylon =
(
(
   ("person$" OR "people$" OR "adult$") 
   NEAR/3 ("vulnerable" OR "marginali$ed" OR "disadvantaged" OR "discriminated" OR "displaced*" OR "disabled" OR "disabilities" OR "disability" OR "patient$" OR "trans" OR "intersex" OR "unemployed" OR "older" OR "elderly" OR "indigenous" OR "low* income" OR "poor" OR "poorest")
) 
OR "ethnic minorit*" OR "minority group$"
OR "refugee$" OR "migrant$" OR "immigrant$" OR "asylum*"
OR "indigenous group$" 
OR "child" OR "children" OR "infant$" OR "babies" OR "newborn$" OR "toddler$" OR "youth$" 
OR "women" OR "woman" OR "girls" OR "girl" OR "pregnant" 
OR "sexual minorit*" OR "LGBT*" OR "lesbian$" OR "gay" OR "bisexual" OR "transgender*"
OR "living with HIV" OR "living with AIDS"
OR "the vulnerable" OR "vulnerable group$" OR "vulnerable communit*" OR "marginali?ed group$" OR "marginali$ed communit*"
OR "the poor" OR "rural poor" OR "urban poor" OR "working poor" OR "destitute" OR "living in poverty" 
)
```

**Comment by Caroline-A** [comment]
- [ ] SDG1
- [ ] SDG2
- [ ] SDG4
- [ ] SDG11
