### ISSUE TITLE
Terms for Basic Services

### ISSUE THREAD

**Issue by Caroline-A** [SDGforskning/SDGstrings_wos#8]
We need to talk though the approach we use for basic services - is it consistent? should it be standardised?

**Comment by hmbjerkan** [comment]
Key questions:

- Level of detail: Basic services is a well established concept, but includes a myriad of subtopics and related concepts. Including detailed terms may introduce noise, but is likely to produce more and better results.
- Adapting to SDG theme/context: Basic services are related to the SDG context, and so the decision is whether to standardise or tailor to context. For SDG 11, the main focus is improving housing in slums or deprived areas, while SDG 1 is more focused on welfare and economic resources. Testing will show how this works out for each target/SDG.

**Comment by MartaLor** [comment]
1.4 By 2030, **ensure** that all men and women, in particular the poor and the vulnerable, have **equal rights** to economic resources, as well as **access to basic services**, ownership and control over land and other forms of property, inheritance, natural resources, appropriate new technology and financial services, including microfinance
11.1 By 2030, **ensure access** for all to **adequate, safe and affordable** housing and **basic services** and upgrade slums


what is the action here? 
1.4 ensure access in string

    ("ensure" OR "establish*" OR "propose*" OR "implement*" OR "plan" OR "plans" OR "planned" OR "planning" OR "adopt*" 
   OR "introduc*" OR "build*" OR                         "develop" OR "development" OR "attain*" OR  "achiev*" OR "improv*" OR 
   "strengthen*" OR "increas*" 
    )
    NEAR/10
    ("access*" OR "equitab*" OR "equity" OR "equality"
      OR "equal" OR "share" OR "sharing" OR "affordab*" OR "right$" 
    )

11.1 access in string
    (access)

basic services: 
general idea: extent synonyms but keep to an general level 
      ("basic" NEAR/3 "service$") 
      OR "clean water" OR ("drinking water" NEAR/3 ("service$" OR "source$" OR "facilit*" OR "basic")) 
      OR "sanitation service$" OR "sanitation facilit$" or "toilet facilit$" OR "basic sanitation" 
      OR "hygiene facilit*" OR "hygiene service*" OR "handwashing facility" OR "hand-washing facility" 
      OR "clean fuels" OR "clean technology" OR "basic electricity" OR "modern energy"   
      OR "basic mobility" OR "transport* system*" OR "transport* infrastructure*" OR "public transport*" 
      OR (("waste" OR "garbage" or "rubbish") NEAR/1 ("collection" OR "management") NEAR/1 ("service$" OR "facilit*")) 
      OR "health care" OR "health-care" OR "healthcare" OR "health service$" OR "medical service$" OR "medical care" 
      OR "basic education" OR "education services" OR "schooling services" OR "education system" OR "school system" 
      OR  "basic information services" OR "basic telecommunication services" OR "basic mobile services" 
    )

**Comment by MartaLor** [comment]
In 11 not linked to housing, I believe it should be. in 1 linked to the poor

**Comment by Caroline-A** [comment]
We will use the same string for both SDG 11 and SDG 1 - in 1 it should be connected to the poor/poverty, in 11 it should be connected to housing.

**Comment by Caroline-A** [comment]
I tried to have a go at making the string a little more flexible while I was looking at SDG1, it's not a big difference but finds a few extra results. See what you think Håkon. I think that some of these terms work for SDG 1 when combined with poor/vulnerable, but will not necessarily when combined with cities(?) (e.g. transport infrastructure). 
Marta's terms came from UN Statistics Division SDG Indicators Metadata Repository, 2022 https://unstats.un.org/sdgs/metadata/files/Metadata-01-04-01.pdf , but I found this presentation which also helped a little https://www.unescap.org/sites/default/files/Indicator%201.4.1_Basic%20Services.pdf 
```
(
("basic" NEAR/2 ("service$" OR "facility" OR "facilities"))
OR 
(("drinking water" OR "sanitation" OR "hygiene" OR "toilet" OR "handwashing" OR "hand-washing" OR "sewage")
	NEAR/2 ("service$" OR "facility" OR "facilities" OR "basic" OR "safe")
)
OR "improved drinking water" OR "improved source$ of drinking water" OR "clean drinking water" OR "clean water"
OR 
(("waste" OR "garbage" OR "rubbish") 
	NEAR/2 ("service$" OR "facility" OR "facilities")
)
OR
(("health" OR "medical")
	NEAR/2 ("service$" OR "facility" OR "facilities" OR "basic" OR "essential" OR "primary" OR "care")
)
OR "healthcare"
OR 
(("education*" OR "school*")
	NEAR/2 ("service$" OR "facility" OR "facilities" OR "basic" OR "primary")
)
OR 
(("basic information" OR "telecommunication" OR "basic communication" OR "ICT")
	NEAR/2 ("service$" OR "facility" OR "facilities" OR "infrastructure")
)
OR "electricity service$" OR "energy service$" OR "modern energy" OR "clean fuel$" OR "clean energy"
OR "public open space$" OR "public space$"
OR "basic mobility" OR "urban mobility" OR "rural mobility" OR "all-season road$"
OR ("transport*" NEAR/2 ("service$" OR "infrastructure" OR "system$" OR "public"))
)
```

**Comment by Caroline-A** [comment]
- [ ] SDG1
- [ ] SDG4
- [ ] SDG11
